Plug 'scrooloose/nerdcommenter'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
" Plug 'godlygeek/tabular'
Plug 'Townk/vim-autoclose'
Plug 'gilsondev/searchtasks.vim'
Plug 'Shougo/neocomplete.vim'
" Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-surround'
" Plug 'editorconfig/editorconfig-vim'
Plug 'aquach/vim-http-client'
