Plug 'scrooloose/nerdcommenter'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'Townk/vim-autoclose'
Plug 'gilsondev/searchtasks.vim'
Plug 'Shougo/neocomplete.vim'
" Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-surround'
Plug 'wellle/targets.vim'
Plug 'jceb/vim-orgmode'
Plug 'unblevable/quick-scope'
" Plug 'editorconfig/editorconfig-vim'

Plug 'vimwiki/vimwiki'
