Plug 'dracula/vim'
" Plug 'wadackel/vim-dogrun'
Plug 'cocopon/iceberg.vim'
Plug 'phenax/palenight.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
Plug 'mkarmona/colorsbox'
