#! /bin/sh
# TODO
# * Multimonitor
# * Assign workspace to applications
# * Run application only on session start



##### Autostart

# Key daemon
killall -9 sxhkd;
sxhkd &

# Compositor
killall -9 compton;
compton --config ~/compton.conf &

# Notification manager
killall -9 dunst;
dunst -config ~/.config/dunst/dunstrc &

killall -9 polybar;
polybar primary &

# killall -9 dzen2;
# ~/scripts/dzen2bar/start.sh &

# Wallpaper
~/.fehbg &

# Network manager applet
nm-applet &


##### Workspace config

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# MONITORS=$(bspc query -M --names);
# MONITOR_COUNT=$(echo "$MONITORS" | wc -l);
# if [[ "$MONITOR_COUNT" == 2 ]]; then
  # MON_PRIMARY="eDP-1"
  # MON_SECONDARY="HDMI-1"
  # bspc monitor $MON_PRIMARY -d 1 2 3 4 5
  # bspc monitor $MON_SECONDARY -d 6 7 8 9 10
# else
  # bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# fi



##### UI config

bspc config border_width         0
bspc config window_gap           12
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config bottom_padding       20
# bspc config top_padding          0


##### Layouts config
bspc config split_ratio            0.6



##### Node rules

# bspc rule -a Spotify desktop='^10'
bspc rule -a "brave-browser" desktop='^6'



##### Initialized applications


