#!/usr/bin/env bash

bspc rule -r "*";

source $HOME/.config/autostart.sh;

##### Autostart {{{
  run polybar primary;
# }}}


##### Workspace/Monitor config {{{
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10

  # Reassign_monitor
  #   If has secondary monitor
  #     Then assign workspace Primary = 1-5, Secondary = 6-10
  #     Else assign workspace Primary 1-10
  # Reassign monitor
  # On monitor {add,remove}
  #   Reassign monitor (by name)
  #   Swap old monitor workspaces into new

  bspc config remove_disabled_monitors    true
  bspc config remove_unplugged_monitors   true
  bspc config merge_overlapping_monitors  true
# }}}


##### UI config {{{
  highlight_color=$(xresources "*.accent")
  bspc config normal_border_color $(xresources "*.background")
  bspc config focused_border_color $highlight_color
  bspc config active_border_color $highlight_color
  bspc config presel_feedback_color	$highlight_color

  bspc config border_width         1
  bspc config window_gap           4
  # bspc config top_padding          0
  # bspc config bottom_padding       0

  bspc config single_monocle       true
  bspc config borderless_monocle   true
  bspc config gapless_monocle      true

  # bspc config pointer_follows_focus   true
  bspc config pointer_follows_monitor   true
  bspc config pointer_modifier          lock
  bspc config pointer_action1           move
  bspc config pointer_action2           resize_side
  bspc config pointer_action3           resize_corner
  bspc config click_to_focus            any
# }}}


##### Layouts config {{{
  bspc config automatic_scheme  alternate # longest_side|alternate|spiral
  bspc config initial_polarity  second_child

  bspc config split_ratio          0.6

  # Initialize layouts
  bsp-layout set tall 1
  bsp-layout set tall 2
# }}}


##### Node rules {{{
  on_startup bspc rule -a "qutebrowser" -o desktop="6";

  bspc config external_rules_command "$HOME/.config/bspwm/external_rules"
# }}}


disown;
