#!/usr/bin/env sh

updates=0;

YAY="yay --sudo=dsudo";

prompt() { notify-send -a "System Update" "$1"; }

prompt "Preparing to start an update. Enter your password to continue";
sensible-terminal -e sh -c "$YAY -Syyu";
prompt "Update complete";

