#!/usr/bin/env sh

updates=0;
yay -Syy && updates="$(yay -Qu)";
update_count=$(echo "$updates" | sed '/^$/d' | wc -l);

[[ "$update_count" = 0 ]] && notify-send "No packages to update" && \
  exit 0;

notify-send \
  -a "Updatings $update_count packages" \
  "$updates";

sensible-terminal -e sh -c 'yay -Syyu --sudo=dsudo';

notify-send \
  -a "System updated" \
  "$update_count packages updated";

